### ISSUE TITLE
Wrong devices display order in multidevice node

### ISSUE THREAD

**Issue by jacek12345** [espressif/esp-rainmaker-ios#11]
It is not displayed in order like device create order. In Android app, it is.
App version: v2.7.0 (6f004b8)

**Comment by jacek12345** [comment]
Can You confirm this issue?

**Comment by vikas-chandra-mnnit** [comment]
@jacek12345 Can you please describe the issue in more detail with screenshots? Thanks.

**Comment by jacek12345** [comment]
Trying with multi_device example. There are 4 devices created and added to node as follows:
1. switch_device 
2. light_device 
3. fan_device 
4. temp_sensor_device 

In app, there is different device order:
1. fan_device 
2. light_device 
3. switch_device 
4. temp_sensor_device 

code (from multi_device example)
```
 /* Create a Switch device and add the relevant parameters to it */
    switch_device = esp_rmaker_switch_device_create("Switch", NULL, DEFAULT_SWITCH_POWER);
    esp_rmaker_device_add_cb(switch_device, write_cb, NULL);
    esp_rmaker_node_add_device(node, switch_device);

    /* Create a Light device and add the relevant parameters to it */
    light_device = esp_rmaker_lightbulb_device_create("Light", NULL, DEFAULT_LIGHT_POWER);
    esp_rmaker_device_add_cb(light_device, write_cb, NULL);
    
    esp_rmaker_device_add_param(light_device,
            esp_rmaker_brightness_param_create(ESP_RMAKER_DEF_BRIGHTNESS_NAME, DEFAULT_LIGHT_BRIGHTNESS));
    
    esp_rmaker_device_add_attribute(light_device, "Serial Number", "012345");
    esp_rmaker_device_add_attribute(light_device, "MAC", "xx:yy:zz:aa:bb:cc");

    esp_rmaker_node_add_device(node, light_device);
    
    /* Create a Fan device and add the relevant parameters to it */
    fan_device = esp_rmaker_fan_device_create("Fan", NULL, DEFAULT_FAN_POWER);
    esp_rmaker_device_add_cb(fan_device, write_cb, NULL);
    esp_rmaker_device_add_param(fan_device, esp_rmaker_speed_param_create(ESP_RMAKER_DEF_SPEED_NAME, DEFAULT_FAN_SPEED));
    esp_rmaker_node_add_device(node, fan_device);
    
    /* Create a Temperature Sensor device and add the relevant parameters to it */
    temp_sensor_device = esp_rmaker_temp_sensor_device_create("Temperature Sensor", NULL, app_get_current_temperature());
    esp_rmaker_node_add_device(node, temp_sensor_device);
```
On the iOS app:
![File (4)](https://user-images.githubusercontent.com/34368502/183641891-f9ad73a9-6926-4e23-8424-c1a27afb8fff.jpg)

Also from monitor console - Reporting devices are in proper order:
`I (5283) esp_rmaker_param: Reporting params (init): {"Switch":{"Name":"Switch","Power":true},"Light":{"Name":"Light","Power":true,"Brightness":25},"Fan":{"Name":"Fan","Power":false,"Speed":3},"Temperature Sensor":{"Name":"Temperature Sensor","Temperature":25.00000},"Time":{"TZ":"","TZ-POSIX":""},"Schedule":{"Schedules":[]},"Scenes":{"Scenes":[]},"Local Control":{"POP":"536ad290","Type":1}}`

**Comment by vikas-chandra-mnnit** [comment]
@jacek12345 In iOS, the device list for a multidevice node is sorted by device name in the app. This was done to keep the device ordering same every time user reloads the Home screen. Let me know if you want more information in this regard.

**Comment by jacek12345** [comment]
Thank You for clarification.
