### ISSUE TITLE
Wrong icon when ESP_RMAKER_UI_TRIGGER param set as primary

### ISSUE THREAD

**Issue by jacek12345** [espressif/esp-rainmaker-ios#12]
It is wrong icon (POWER) on the device main tab. Inside tab, there is proper TRIGGER icon.  Problem only on iOS app. 
App version: v2.7.0 (6f004b8)

**Comment by vikas-chandra-mnnit** [comment]
Hi @jacek12345, thanks for reporting this. We have not handled the trigger param in the iOS Home screen. This will be fixed in the upcoming releases.
