### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Vishnu2201** [espressif/esp-rainmaker-ios#2]
When I run ESPRainmaker it shows 4 error as the follows
Type 'ConnectViewController' does not conform to protocol 'ESPDeviceConnectionDelegate'
Type 'ProvisionLandingViewController' does not conform to protocol 'ESPDeviceConnectionDelegate'
Type 'ScannerViewController' does not conform to protocol 'ESPDeviceConnectionDelegate'
Command CompileSwift failed with a nonzero exit code
Can you please walk me through these error correction
<img width="1400" alt="Screenshot 2021-05-21 at 9 52 52 AM" src="https://user-images.githubusercontent.com/30022347/119081763-51400c00-ba1a-11eb-8300-421d6a48cb62.png">

**Comment by vikas-chandra-mnnit** [comment]
@Vishnu2201 You need to edit your PodFile to use older version of the ESPProvision library.

  pod 'ESPProvision', '2.0.9'

Do `pod clean` and `pod install` and rebuild the app.

**Comment by Vishnu2201** [comment]
<img width="1398" alt="Screenshot 2021-05-21 at 5 44 26 PM" src="https://user-images.githubusercontent.com/30022347/119135550-32626980-ba5c-11eb-8254-fd3e77882395.png">
Am getting a single error now as 
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by vikas-chandra-mnnit** [comment]
@Vishnu2201 You need to instal SwiftFormat using `brew install swiftformat`.

**Comment by Vishnu2201** [comment]
Thankyou its working
