### ISSUE TITLE
Disable third party login options

### ISSUE THREAD

**Issue by bretfrederick-pvmit** [espressif/esp-rainmaker-ios#7]
Hello,

I have a private instance of Rainmaker backend deployed in AWS.  Everything works well with the iOS app, but I would like to only allow account sign up using e-mail.  I would like to disable the Github, Apple, and Google third party identity providers in the iOS sign up screen.  How can I do this?

**Comment by vikas-chandra-mnnit** [comment]
Hi @bretfrederick-pvmit, we have not yet provided the option to make the 3rd party login as optional in the app. However, if you want to disable it you can do it simply by removing the GitHub, Apple, and Google buttons from the UI in the Login.storyboard and removing the associated methods from SignInViewController.swift. Do let us know if you require any additional help in this regard.

**Comment by bretfrederick-pvmit** [comment]
OK, thanks very much.  I'll go the route of changing the storyboard.
