### ISSUE TITLE
How can I avoid "Bluetooth pairing request" alert on iOS

### ISSUE THREAD

**Issue by ssqcharlie540** [espressif/esp-rainmaker-ios#9]
iOS are prompting with the "Bluetooth pairing request" alert before first call "ESPBleTransport.peripheral(_:didWriteValueFor:error:)" .

How can I avoid "Bluetooth pairing request" alert on iOS ?

**Comment by shahpiyushv** [comment]
@ssqcharlie540 Please try disabling [CONFIG_WIFI_PROV_BLE_FORCE_ENCRYPTION](https://github.com/espressif/esp-idf/blob/01d014c42def8d0c19e1ce55c07de6761e092ffa/components/wifi_provisioning/Kconfig#L34), which you can find under Component Config -> Wi-Fi Provisioning Manager.

**Comment by ssqcharlie540** [comment]
> @ssqcharlie540 Please try disabling [CONFIG_WIFI_PROV_BLE_FORCE_ENCRYPTION](https://github.com/espressif/esp-idf/blob/01d014c42def8d0c19e1ce55c07de6761e092ffa/components/wifi_provisioning/Kconfig#L34), which you can find under Component Config -> Wi-Fi Provisioning Manager.

Problem solved, thanks a lot
